version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
  build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
    - appspec.yml
    